version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - api.env
    ports:
      - 8000:8000
    volumes:
      - .:/app-dev

  redis:
    image: redis
    ports:
      - 6379:6279